//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace AlorTest.Model;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class Value {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string ValueField {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ListType {
    
    private string ValueField;
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ListTypeValue {
        get {
            return this.ValueField;
        }
        set {
            this.ValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class LastDayUpdated {
    
    private Value[] ValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VALUE", IsNullable=true)]
    public Value[] VALUE {
        get {
            return this.ValueField;
        }
        set {
            this.ValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ConsolidatedList {
    
    private Individual[] _individualsList;
    
    private Entity[] _entitiesList;
    
    private string dateGeneratedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("INDIVIDUAL", typeof(Individual), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Individual[] IndividualsList {
        get {
            return this._individualsList;
        }
        set {
            this._individualsList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ENTITY", typeof(Entity), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Entity[] EntitiesList {
        get {
            return this._entitiesList;
        }
        set {
            this._entitiesList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DateGenerated {
        get {
            return this.dateGeneratedField;
        }
        set {
            this.dateGeneratedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Individual {
    
    private string _dataId;
    
    private string _versionNum;
    
    private string _firstName;
    
    private string _secondName;
    
    private string _thirdName;
    
    private string _fourthName;
    
    private string _unListType;
    
    private string _reference_number;
    
    private string _listedOn;
    
    private string _gender;
    
    private string _nameOriginalScript;
    
    private string _comments1;
    
    private string _sortKey;
    
    private string _sortKeyLastModified;
    
    private Value[] _title;
    
    private Value[] _designation;
    
    private Value[] _nationality;
    
    private Value[] _listType;
    
    private Value[] _lastDayUpdated;
    
    private IndividualAlias[] _individualAliasList;
    
    private IndividualAddress[] _individualAddressList;
    
    private IndividualDateOfBirth[] _individualDateOfBirthList;
    
    private IndividualPlaceOfBirth[] _individualPlaceOfBirthList;
    
    private IndividualDocument[] _individualDocumentList;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DATAID", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataId {
        get {
            return this._dataId;
        }
        set {
            this._dataId = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VERSIONNUM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VersionNum
    {
        get {
            return this._versionNum;
        }
        set {
            this._versionNum = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIRST_NAME", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FirstName {
        get {
            return this._firstName;
        }
        set {
            this._firstName = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SECOND_NAME", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SecondName {
        get {
            return this._secondName;
        }
        set {
            this._secondName = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("THIRD_NAME", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ThirdName {
        get {
            return this._thirdName;
        }
        set {
            this._thirdName = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FOURTH_NAME", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FourthName {
        get {
            return this._fourthName;
        }
        set {
            this._fourthName = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UN_LIST_TYPE", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UnListType {
        get {
            return this._unListType;
        }
        set {
            this._unListType = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("REFERENCE_NUMBER", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReferenceNumber {
        get {
            return this._reference_number;
        }
        set {
            this._reference_number = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LISTED_ON", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ListedOn {
        get {
            return this._listedOn;
        }
        set {
            this._listedOn = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GENDER", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Gender {
        get {
            return this._gender;
        }
        set {
            this._gender = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NAME_ORIGINAL_SCRIPT", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NameOriginalScript {
        get {
            return this._nameOriginalScript;
        }
        set {
            this._nameOriginalScript = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("COMMENTS1", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comments1 {
        get {
            return this._comments1;
        }
        set {
            this._comments1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SORT_KEY", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortKey {
        get {
            return this._sortKey;
        }
        set {
            this._sortKey = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SORT_KEY_LAST_MOD", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SortKeyLastMod {
        get {
            return this._sortKeyLastModified;
        }
        set {
            this._sortKeyLastModified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("TITLE", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[] Title {
        get {
            return this._title;
        }
        set {
            this._title = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("DESIGNATION", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[] Designation {
        get {
            return this._designation;
        }
        set {
            this._designation = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("NATIONALITY", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[] Nationality {
        get {
            return this._nationality;
        }
        set {
            this._nationality = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("LIST_TYPE", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[] ListType {
        get {
            return this._listType;
        }
        set {
            this._listType = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute("LAST_DAY_UPDATED", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[] LastDayUpdated {
        get {
            return this._lastDayUpdated;
        }
        set {
            this._lastDayUpdated = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INDIVIDUAL_ALIAS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IndividualAlias[] IndividualAlias {
        get {
            return this._individualAliasList;
        }
        set {
            this._individualAliasList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INDIVIDUAL_ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IndividualAddress[] IndividualAddress
    {
        get {
            return this._individualAddressList;
        }
        set {
            this._individualAddressList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INDIVIDUAL_DATE_OF_BIRTH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IndividualDateOfBirth[] IndividualDateOfBirth {
        get {
            return this._individualDateOfBirthList;
        }
        set {
            this._individualDateOfBirthList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INDIVIDUAL_PLACE_OF_BIRTH", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IndividualPlaceOfBirth[] IndividualPlaceOfBirth
    {
        get {
            return this._individualPlaceOfBirthList;
        }
        set {
            this._individualPlaceOfBirthList = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INDIVIDUAL_DOCUMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IndividualDocument[] IndividualDocument {
        get {
            return this._individualDocumentList;
        }
        set {
            this._individualDocumentList = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IndividualAlias {
    
    private string qUALITYField;
    
    private string aLIAS_NAMEField;
    
    private string cITY_OF_BIRTHField;
    
    private string cOUNTRY_OF_BIRTHField;
    
    private string nOTEField;
    
    private string dATE_OF_BIRTHField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QUALITY {
        get {
            return this.qUALITYField;
        }
        set {
            this.qUALITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ALIAS_NAME {
        get {
            return this.aLIAS_NAMEField;
        }
        set {
            this.aLIAS_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY_OF_BIRTH {
        get {
            return this.cITY_OF_BIRTHField;
        }
        set {
            this.cITY_OF_BIRTHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNTRY_OF_BIRTH {
        get {
            return this.cOUNTRY_OF_BIRTHField;
        }
        set {
            this.cOUNTRY_OF_BIRTHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NOTE {
        get {
            return this.nOTEField;
        }
        set {
            this.nOTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DATE_OF_BIRTH {
        get {
            return this.dATE_OF_BIRTHField;
        }
        set {
            this.dATE_OF_BIRTHField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IndividualAddress {
    
    private string nOTEField;
    
    private string sTREETField;
    
    private string sTATE_PROVINCEField;
    
    private string cITYField;
    
    private string cOUNTRYField;
    
    private string zIP_CODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NOTE {
        get {
            return this.nOTEField;
        }
        set {
            this.nOTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STREET {
        get {
            return this.sTREETField;
        }
        set {
            this.sTREETField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STATE_PROVINCE {
        get {
            return this.sTATE_PROVINCEField;
        }
        set {
            this.sTATE_PROVINCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY {
        get {
            return this.cITYField;
        }
        set {
            this.cITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNTRY {
        get {
            return this.cOUNTRYField;
        }
        set {
            this.cOUNTRYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZIP_CODE {
        get {
            return this.zIP_CODEField;
        }
        set {
            this.zIP_CODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IndividualDateOfBirth {
    
    private string _typeOfDate;
    
    private string _date;
    
    private string _fromYear;
    
    private string _toYear;
    
    private string _note;
    
    private string _year;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TYPE_OF_DATE", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TypeOfDate {
        get {
            return this._typeOfDate;
        }
        set {
            this._typeOfDate = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Date {
        get {
            return this._date;
        }
        set {
            this._date = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FROM_YEAR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromYear {
        get {
            return this._fromYear;
        }
        set {
            this._fromYear = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TO_YEAR", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ToYear {
        get {
            return this._toYear;
        }
        set {
            this._toYear = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NOTE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Note {
        get {
            return this._note;
        }
        set {
            this._note = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("YEAR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Year {
        get {
            return this._year;
        }
        set {
            this._year = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IndividualPlaceOfBirth {
    
    private string _street;
    
    private string _city;
    
    private string _stateProvince;
    
    private string _note;
    
    private string _country;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STREET", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Street {
        get {
            return this._street;
        }
        set {
            this._street = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string City {
        get {
            return this._city;
        }
        set {
            this._city = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STATE_PROVINCE", Form =System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StateProvince {
        get {
            return this._stateProvince;
        }
        set {
            this._stateProvince = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NOTE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Note {
        get {
            return this._note;
        }
        set {
            this._note = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("COUNTRY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Country {
        get {
            return this._country;
        }
        set {
            this._country = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IndividualDocument {
    
    private string tYPE_OF_DOCUMENTField;
    
    private string tYPE_OF_DOCUMENT2Field;
    
    private string nOTEField;
    
    private string nUMBERField;
    
    private string iSSUING_COUNTRYField;
    
    private string dATE_OF_ISSUEField;
    
    private string cITY_OF_ISSUEField;
    
    private string cOUNTRY_OF_ISSUEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TYPE_OF_DOCUMENT {
        get {
            return this.tYPE_OF_DOCUMENTField;
        }
        set {
            this.tYPE_OF_DOCUMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TYPE_OF_DOCUMENT2 {
        get {
            return this.tYPE_OF_DOCUMENT2Field;
        }
        set {
            this.tYPE_OF_DOCUMENT2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NOTE {
        get {
            return this.nOTEField;
        }
        set {
            this.nOTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NUMBER {
        get {
            return this.nUMBERField;
        }
        set {
            this.nUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ISSUING_COUNTRY {
        get {
            return this.iSSUING_COUNTRYField;
        }
        set {
            this.iSSUING_COUNTRYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DATE_OF_ISSUE {
        get {
            return this.dATE_OF_ISSUEField;
        }
        set {
            this.dATE_OF_ISSUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY_OF_ISSUE {
        get {
            return this.cITY_OF_ISSUEField;
        }
        set {
            this.cITY_OF_ISSUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNTRY_OF_ISSUE {
        get {
            return this.cOUNTRY_OF_ISSUEField;
        }
        set {
            this.cOUNTRY_OF_ISSUEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Entity {
    
    private string dATAIDField;
    
    private string vERSIONNUMField;
    
    private string fIRST_NAMEField;
    
    private string uN_LIST_TYPEField;
    
    private string rEFERENCE_NUMBERField;
    
    private string lISTED_ONField;
    
    private string nAME_ORIGINAL_SCRIPTField;
    
    private string cOMMENTS1Field;
    
    private string sORT_KEYField;
    
    private string sORT_KEY_LAST_MODField;
    
    private ListType[] lIST_TYPEField;
    
    private Value[][] lAST_DAY_UPDATEDField;
    
    private CONSOLIDATED_LISTENTITIESENTITYENTITY_ALIAS[] eNTITY_ALIASField;
    
    private CONSOLIDATED_LISTENTITIESENTITYENTITY_ADDRESS[] eNTITY_ADDRESSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DATAID {
        get {
            return this.dATAIDField;
        }
        set {
            this.dATAIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VERSIONNUM {
        get {
            return this.vERSIONNUMField;
        }
        set {
            this.vERSIONNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FIRST_NAME {
        get {
            return this.fIRST_NAMEField;
        }
        set {
            this.fIRST_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UN_LIST_TYPE {
        get {
            return this.uN_LIST_TYPEField;
        }
        set {
            this.uN_LIST_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string REFERENCE_NUMBER {
        get {
            return this.rEFERENCE_NUMBERField;
        }
        set {
            this.rEFERENCE_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LISTED_ON {
        get {
            return this.lISTED_ONField;
        }
        set {
            this.lISTED_ONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NAME_ORIGINAL_SCRIPT {
        get {
            return this.nAME_ORIGINAL_SCRIPTField;
        }
        set {
            this.nAME_ORIGINAL_SCRIPTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENTS1 {
        get {
            return this.cOMMENTS1Field;
        }
        set {
            this.cOMMENTS1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SORT_KEY {
        get {
            return this.sORT_KEYField;
        }
        set {
            this.sORT_KEYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SORT_KEY_LAST_MOD {
        get {
            return this.sORT_KEY_LAST_MODField;
        }
        set {
            this.sORT_KEY_LAST_MODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LIST_TYPE")]
    public ListType[] LIST_TYPE {
        get {
            return this.lIST_TYPEField;
        }
        set {
            this.lIST_TYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("VALUE", typeof(Value))]
    public Value[][] LAST_DAY_UPDATED {
        get {
            return this.lAST_DAY_UPDATEDField;
        }
        set {
            this.lAST_DAY_UPDATEDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ENTITY_ALIAS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CONSOLIDATED_LISTENTITIESENTITYENTITY_ALIAS[] ENTITY_ALIAS {
        get {
            return this.eNTITY_ALIASField;
        }
        set {
            this.eNTITY_ALIASField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ENTITY_ADDRESS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CONSOLIDATED_LISTENTITIESENTITYENTITY_ADDRESS[] ENTITY_ADDRESS {
        get {
            return this.eNTITY_ADDRESSField;
        }
        set {
            this.eNTITY_ADDRESSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CONSOLIDATED_LISTENTITIESENTITYENTITY_ALIAS {
    
    private string qUALITYField;
    
    private string aLIAS_NAMEField;
    
    private string nOTEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string QUALITY {
        get {
            return this.qUALITYField;
        }
        set {
            this.qUALITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ALIAS_NAME {
        get {
            return this.aLIAS_NAMEField;
        }
        set {
            this.aLIAS_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NOTE {
        get {
            return this.nOTEField;
        }
        set {
            this.nOTEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class CONSOLIDATED_LISTENTITIESENTITYENTITY_ADDRESS {
    
    private string sTREETField;
    
    private string cITYField;
    
    private string sTATE_PROVINCEField;
    
    private string zIP_CODEField;
    
    private string cOUNTRYField;
    
    private string nOTEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STREET {
        get {
            return this.sTREETField;
        }
        set {
            this.sTREETField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY {
        get {
            return this.cITYField;
        }
        set {
            this.cITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STATE_PROVINCE {
        get {
            return this.sTATE_PROVINCEField;
        }
        set {
            this.sTATE_PROVINCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZIP_CODE {
        get {
            return this.zIP_CODEField;
        }
        set {
            this.zIP_CODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNTRY {
        get {
            return this.cOUNTRYField;
        }
        set {
            this.cOUNTRYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NOTE {
        get {
            return this.nOTEField;
        }
        set {
            this.nOTEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CONSOLIDATED_LIST", typeof(ConsolidatedList))]
    [System.Xml.Serialization.XmlElementAttribute("LAST_DAY_UPDATED", typeof(Value[]))]
    [System.Xml.Serialization.XmlElementAttribute("LIST_TYPE", typeof(ListType))]
    [System.Xml.Serialization.XmlElementAttribute("VALUE", typeof(Value), IsNullable=true)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
